# Generated by Django 3.2.18 on 2023-06-01 21:56

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='doctores.usuario')),
                ('sex', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'No Binario')], default='M', max_length=1, null=True)),
                ('birthday', models.DateField(blank=True, default='2000-01-01', null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=22, null=True)),
                ('address', models.CharField(default=None, max_length=50, null=True)),
                ('vip', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Pacientes',
            },
            bases=('doctores.usuario',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id_consulta', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('attended', models.BooleanField(default=False)),
                ('observations', models.TextField(blank=True, default=None, null=True)),
                ('dni_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctores.doctor')),
                ('dni_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
                ('id_calendario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctores.calendario')),
            ],
            options={
                'verbose_name_plural': 'Consultas',
            },
        ),
    ]
