# Generated by Django 3.2.18 on 2023-06-15 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id_consulta', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('attended', models.BooleanField(default=False)),
                ('observations', models.TextField(blank=True, default=None, null=True)),
                ('id_calendario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctores.calendario')),
                ('id_doctor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctores.doctor')),
            ],
            options={
                'verbose_name_plural': 'Consultas',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='doctores.usuario')),
                ('dni', models.IntegerField(default=1, unique=True, verbose_name='DNI')),
                ('sex', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'No Binario')], default='M', max_length=1, null=True, verbose_name='Sexo')),
                ('birthdate', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('phone_number', models.CharField(blank=True, default=None, max_length=22, null=True, verbose_name='Telefono')),
                ('address', models.CharField(max_length=50, verbose_name='Direccion')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('postal', models.CharField(max_length=10, verbose_name='Codigo Postal')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('vip', models.BooleanField(default=False)),
                ('doctores', models.ManyToManyField(through='pacientes.Consulta', to='doctores.Doctor')),
            ],
            options={
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.AddField(
            model_name='consulta',
            name='id_paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente'),
        ),
    ]
