# Generated by Django 3.2.18 on 2023-06-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(default=True, max_length=50, verbose_name='Apellido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='email',
            field=models.EmailField(default=True, max_length=50, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(default=True, max_length=50, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
