# Generated by Django 3.2.18 on 2023-05-23 19:33

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0002_auto_20230523_1633'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name_plural': 'Pacientes'},
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='id',
        ),
        migrations.AddField(
            model_name='paciente',
            name='address',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='birthday',
            field=models.DateField(blank=True, default='2000-01-01', null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='password',
            field=models.CharField(default=models.IntegerField(primary_key=True, serialize=False), max_length=50),
        ),
        migrations.AddField(
            model_name='paciente',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sex',
            field=models.CharField(blank=True, default='Male', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dni',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id_consulta', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time_start', models.TimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('attended', models.BooleanField(default=False)),
                ('dni_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
                ('license_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctores.doctor')),
            ],
            options={
                'verbose_name_plural': 'Consultas',
            },
        ),
    ]
