# Generated by Django 3.2.18 on 2023-05-30 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0002_auto_20230523_1633'),
        ('pacientes', '0002_auto_20230523_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='date',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='time_start',
        ),
        migrations.AddField(
            model_name='consulta',
            name='id_calendario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctores.calendario'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='observations',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
