# Generated by Django 3.2.18 on 2023-06-09 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pacientes', '0002_auto_20230605_1542'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='paciente',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='usuario_ptr',
        ),
        migrations.AddField(
            model_name='paciente',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dni_pac',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
