# Generated by Django 3.2.18 on 2023-06-20 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_auto_20230616_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'permissions': [('ver_modulo_paciente', 'Puede acceder a la Aplicacion Pacientes')], 'verbose_name_plural': 'Pacientes'},
        ),
    ]
