# Generated by Django 3.2.18 on 2023-05-30 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0002_auto_20230523_1633'),
        ('pacientes', '0003_auto_20230530_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='id_calendario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctores.calendario'),
        ),
    ]
