# Generated by Django 3.2.18 on 2023-06-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_paciente_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AddField(
            model_name='paciente',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='profile_images'),
        ),
    ]
