# Generated by Django 3.2.18 on 2023-05-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('datecompleted', models.DateTimeField(blank=True, null=True)),
                ('vip', models.BooleanField(default=False)),
            ],
        ),
    ]
