# Generated by Django 3.2.18 on 2023-06-05 18:42

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='doctor',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='calendario',
            old_name='user_doctor',
            new_name='dni_doctor',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.AddField(
            model_name='doctor',
            name='usuario_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='doctores.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='dni_dr',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, unique=True),
        ),
    ]
