# Generated by Django 3.2.18 on 2023-05-23 19:33

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id_calendar', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('hour', models.TimeField()),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Calendarios',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('license', models.IntegerField(primary_key=True, serialize=False)),
                ('dni', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('password', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Doctores',
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_especiality', models.IntegerField(primary_key=True, serialize=False)),
                ('name_especiality', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.DeleteModel(
            name='Consultas',
        ),
        migrations.AddField(
            model_name='doctor',
            name='especiality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctores.especialidad'),
        ),
        migrations.AddField(
            model_name='calendario',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctores.doctor'),
        ),
    ]
