# Generated by Django 3.2.18 on 2023-06-24 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0002_auto_20230616_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='email',
        ),
    ]
