# Generated by Django 3.2.18 on 2023-06-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0003_remove_doctor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='birthdate',
            field=models.DateField(default='2000-01-01', verbose_name='Fecha de Nacimiento'),
        ),
    ]
