# Generated by Django 3.2.18 on 2023-06-09 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0003_auto_20230606_1951'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='doctor',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='usuario_ptr',
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='doctores.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='dni_dr',
            field=models.IntegerField(default=1, unique=True, verbose_name='DNI'),
        ),
    ]
